title: Nina van der Kley
author: ninavdk
email: ninavdk99@gmail.com
description: I’m technically knowledgeable and a people person. I love to learn new things and collaborate with smart people. I want to deliver products that improve the world.

github_username: ninavdk

minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
