title: Nina van der Kley
author: ninavdk
email: ninavdk99@gmail.com
description: Voracious Learner - Quality Warrior

github_username: ninavdk
linkedin_username: ninavdk

minima:
  date_format: "%b %-d, %Y"

header_pages:
 - blog.md
 - contact.html

plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
