title: Nina van der Kley
author: ninavdk
email:
description: Product - Technology - User focus

github_username: ninavdk
linkedin_username: ninavdk

minima:
  date_format: "%b %-d, %Y"

header_pages:
 - contact.html

plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
